package memcheck

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// This file holds the CALIBRATION CORPUS: fixtures whose true token counts were
// measured by the harness itself, and the tests that hold EstimateTokens to
// them.
//
// Why a measured corpus exists at all
// -----------------------------------
// The bug this package was fixed for was a unit error: it compared a byte count
// against a constant that was really a token budget. The obvious way to ship
// that defect again is to replace one uncalibrated number with another and
// verify it by noting that the new number "looks plausible" — which is exactly
// what the broken version already produced. So the estimator is not checked
// against intuition; it is checked against readings taken from the harness.
//
// How the ground truth was obtained
// ---------------------------------
// The harness reports its own token accounting when it refuses an over-cap
// read. Reading a fixture larger than the cap returns, verbatim:
//
//	File content (57023 tokens) exceeds maximum allowed tokens (25000)
//
// That message is the measuring instrument: it names both the file's true token
// count and the cap. Each fixture below was generated by the builder recorded
// beside it, written to disk, and Read; the wantTokens field is the number the
// harness reported. Nothing here is estimated or back-computed.
//
// The cap itself (25000 tokens) was read off the same message, and independently
// falsified in the other direction: a 41082-byte fixture — 1.6x the byte figure
// the old constant held — read back in full, all 527 lines, no truncation.
//
// Regenerating
// ------------
// The builders are deterministic, so the corpus can be rebuilt byte-for-byte:
//
//	MEMCHECK_CORPUS_DIR=/tmp/corpus go test ./internal/memcheck -run TestWriteCorpus
//
// then Read each emitted file with the harness and update wantTokens. Do this
// whenever the harness tokenizer or cap changes — the numbers below are
// observations with a date on them, not constants.

// --- builders -------------------------------------------------------------
//
// Each builds a distinct token-density regime. They deliberately span the range
// from dense punctuation (JSON) to flat prose, because the whole point is that
// bytes-per-token is content-dependent and no single ratio covers the range.

func numberedIndex(n int) string {
	var b strings.Builder
	b.WriteString("# Memory index\n\n")
	for i := 0; i < n; i++ {
		fmt.Fprintf(&b, "- [Memory %d](file-%d.md) — a reasonably sized one-line hook for entry %d\n", i, i, i)
	}
	return b.String()
}

func proseHookIndex(n int) string {
	return "# Memory index\n\n" + strings.Repeat(
		"- [The launchd nondemand spawn wedge](launchd-wedge.md) — a wedged session sits at "+
			"pended nondemand spawn forever and must be revived by hand before anything else works\n", n)
}

func flatProse(n int) string {
	return "# Notes\n\n" + strings.Repeat(
		"The daemon reconciles its view of the world on every heartbeat, comparing what it "+
			"believes is running against what the process table actually reports, and repairs any "+
			"drift it finds without waiting for a human to notice the discrepancy first.\n", n)
}

func denseJSON(n int) string {
	var b strings.Builder
	b.WriteString("[\n")
	for i := 0; i < n; i++ {
		sep := ","
		if i == n-1 {
			sep = ""
		}
		fmt.Fprintf(&b, " {\n  \"id\": \"mg-%04x\",\n  \"status\": \"open\",\n  \"score\": %d\n }%s\n", i, i*7, sep)
	}
	b.WriteString("]")
	return b.String()
}

func emojiIndex(n int) string {
	return "# Notes 🚀\n\n" + strings.Repeat(
		"- ✅ résumé — naïve café façade 日本語テキスト entry with accents and CJK\n", n)
}

func urlIndex(n int) string {
	return "# Refs\n\n" + strings.Repeat(
		"- https://github.com/sourcegraph/zoekt/blob/main/web/templates.go#L158 — /Users/daniel/.pogo/agents/crew/pm-pogo.md\n", n)
}

func mixedIndex(n int) string {
	return "# Memory index\n\n" + strings.Repeat(
		"- [Sandboxing pogod](sandbox.md) — since mg-3dc3/mg-9a1c: no config file means no "+
			"auto-start; `[agents] autostart = false` disables it, and all state honors POGO_HOME=$HOME/.pogo\n", n)
}

// --- the corpus -----------------------------------------------------------

type corpusEntry struct {
	name string
	body string
	// wantTokens is the harness's OWN reported token count for this exact body.
	// Measured, not computed. See the file header for how to re-measure.
	wantTokens int
}

func corpus() []corpusEntry {
	return []corpusEntry{
		{"numbered-index", numberedIndex(1667), 57023},
		{"prose-hook-index", proseHookIndex(700), 42711},
		{"flat-prose", flatProse(900), 62110},
		{"dense-json", denseJSON(1200), 41041},
		{"emoji-cjk", emojiIndex(1400), 46214},
		{"urls-paths", urlIndex(1100), 69310},
		{"mixed-index", mixedIndex(900), 76511},
	}
}

// estimatorTolerance is the error band EstimateTokens is held to across the
// corpus. It is a MEASURED property of the fitted model, not an aspiration: the
// worst residual observed when the coefficients were fitted was ~10.6%, and this
// band is set just above it. Widening this to make a failing test pass would
// defeat its purpose — refit the coefficients instead.
const estimatorTolerance = 0.12

// TestEstimatorMatchesMeasuredCorpus is the calibration test. It holds the
// estimator to token counts the harness reported for these exact bodies. If the
// estimator drifts from observed harness behaviour, this fails.
func TestEstimatorMatchesMeasuredCorpus(t *testing.T) {
	for _, c := range corpus() {
		got := EstimateTokens([]byte(c.body))
		relErr := float64(got-c.wantTokens) / float64(c.wantTokens)
		if relErr > estimatorTolerance || relErr < -estimatorTolerance {
			t.Errorf("%s: estimated %d tokens, harness measured %d (%.1f%% off, tolerance ±%.0f%%)",
				c.name, got, c.wantTokens, relErr*100, estimatorTolerance*100)
		}
	}
}

// TestBytesCannotProxyForTokens is the regression test for the original defect.
// It proves no single bytes-per-token divisor can cover the corpus, which is why
// the estimator is structural rather than a division. If someone "simplifies"
// EstimateTokens back into bytes/N, the measured spread here shows why that
// cannot be made correct.
func TestBytesCannotProxyForTokens(t *testing.T) {
	minRatio, maxRatio := 1e9, 0.0
	var minName, maxName string
	for _, c := range corpus() {
		ratio := float64(len(c.body)) / float64(c.wantTokens)
		if ratio < minRatio {
			minRatio, minName = ratio, c.name
		}
		if ratio > maxRatio {
			maxRatio, maxName = ratio, c.name
		}
	}
	// Any flat divisor must be wrong by at least the spread between the
	// densest and lightest content.
	spread := maxRatio / minRatio
	if spread < 1.5 {
		t.Fatalf("corpus no longer spans a meaningful density range (spread %.2fx); it can no longer demonstrate why a byte proxy fails", spread)
	}
	t.Logf("bytes/token spans %.2f (%s) to %.2f (%s) — %.2fx spread; a flat divisor is wrong by at least this much",
		minRatio, minName, maxRatio, maxName, spread)
}

// TestWarnFractionAbsorbsEstimatorError enforces the safety relationship the
// design depends on: because EstimateTokens can UNDER-estimate, the warn point
// must sit far enough below the cap that a maximally under-estimated file still
// trips the warn before it hits the cliff.
//
// Formally: warn fires at est >= WarnFraction*cap. With a worst-case
// under-estimate U, that means true tokens can reach WarnFraction*cap/(1-U)
// before we notice. That value MUST stay below the cap.
func TestWarnFractionAbsorbsEstimatorError(t *testing.T) {
	worstTrueAtWarn := WarnFraction * float64(HarnessReadCapTokens) / (1 - estimatorTolerance)
	if worstTrueAtWarn >= float64(HarnessReadCapTokens) {
		t.Fatalf("WarnFraction %.2f is too high for an estimator with ±%.0f%% error: a maximally under-estimated index would not warn until %.0f true tokens, at or past the %d-token cliff",
			WarnFraction, estimatorTolerance*100, worstTrueAtWarn, HarnessReadCapTokens)
	}
	t.Logf("worst-case: warn fires by %.0f true tokens, %.0f tokens of headroom below the %d-token cap",
		worstTrueAtWarn, float64(HarnessReadCapTokens)-worstTrueAtWarn, HarnessReadCapTokens)
}

// --- cliff controls -------------------------------------------------------
//
// The corpus test above pins the ESTIMATOR. These two pin the DETECTOR, against
// observed harness behaviour on either side of the real cliff. Both fixtures
// were Read through the harness and the outcome recorded:
//
//	numberedIndex(760) -> 59726 bytes
//	  "File content (25091 tokens) exceeds maximum allowed tokens (25000)"
//	  => the harness REFUSED it. It is genuinely over the cliff.
//
//	numberedIndex(524) -> 41082 bytes
//	  => the harness served it IN FULL, all 527 lines, no truncation.
//	     It is genuinely under the cliff.
//
// Note what the second one proves about the defect being fixed: at 41082 bytes
// it is more than double the old 20000-BYTE warn threshold and well past the
// old 25000-"byte" cap, so the previous check called it a catastrophe. The
// harness read it without complaint. That is the false alarm, demonstrated
// rather than argued.

// TestPositiveControl_FiresOnGenuinelyOverCliffIndex is the control the fix is
// accountable to: an index the harness ACTUALLY refuses must make the detector
// go red. A check that cannot be made to fire on real over-cliff input has not
// been calibrated, only made plausible.
func TestPositiveControl_FiresOnGenuinelyOverCliffIndex(t *testing.T) {
	const measuredTrueTokens = 25091 // harness-reported; it refused this file
	body := []byte(numberedIndex(760))
	if len(body) != 59726 {
		t.Fatalf("fixture drifted from the measured one: %d bytes, want 59726 — the recorded token count no longer applies", len(body))
	}
	if measuredTrueTokens <= HarnessReadCapTokens {
		t.Fatalf("fixture is not actually over the cliff (%d <= %d)", measuredTrueTokens, HarnessReadCapTokens)
	}
	r := Check("MEMORY.md", body)
	if !r.Approaching {
		t.Fatalf("POSITIVE CONTROL FAILED: the harness refuses this index at %d true tokens, but the detector stayed silent (estimated %d, threshold %d)",
			measuredTrueTokens, r.EstTokens, r.ThresholdTokens)
	}
	if len(r.FattestLines) == 0 {
		t.Fatal("fired but named no heavy lines; the warn must give the fix a target")
	}
	t.Logf("over-cliff fixture: %d bytes, %d true tokens (harness refused it), estimated %d, threshold %d — detector RED as required",
		len(body), measuredTrueTokens, r.EstTokens, r.ThresholdTokens)
}

// TestNegativeControl_SilentOnIndexTheHarnessReadsFine is the other half, and
// it is now scoped to the budget it actually measured. An index the harness
// READS in full must not be reported as approaching the READ cliff — that is
// the false alarm mg-b938 removed, and it stays removed.
//
// It asserts ApproachingRead, not Approaching, and the difference is the whole
// of mg-9a89: this same fixture IS over the auto-inject budget (see
// TestTheReadFineFixtureIsAutoInjectTruncated below). Asserting the combined
// flag here would be asserting that a truncating index is healthy.
func TestNegativeControl_SilentOnIndexTheHarnessReadsFine(t *testing.T) {
	body := []byte(numberedIndex(524))
	if len(body) != 41082 {
		t.Fatalf("fixture drifted from the measured one: %d bytes, want 41082", len(body))
	}
	r := Check("MEMORY.md", body)
	if r.ApproachingRead {
		t.Fatalf("FALSE ALARM: the harness reads this %d-byte index in full, but the read check cried cliff (estimated %d tokens, threshold %d)",
			len(body), r.EstTokens, r.ThresholdTokens)
	}
	// The regression guard: the superseded byte logic fired here.
	if len(body) < 20000 {
		t.Fatal("this fixture no longer exercises the original defect — it must exceed the old 20000-byte warn threshold to prove the false alarm is gone")
	}
	t.Logf("under-read-cliff fixture: %d bytes (2x the old 20000-byte warn point), harness read it in full, estimated %d tokens vs threshold %d — read check GREEN as required",
		len(body), r.EstTokens, r.ThresholdTokens)
}

// TestTheReadFineFixtureIsAutoInjectTruncated is the mg-9a89 finding as a test,
// and it is deliberately built on the exact fixture mg-b938 certified healthy.
//
// mg-b938 measured this 41082-byte index against the harness Read tool, watched
// it come back in full, and concluded the detector should stay green on it. All
// of that was correct. It was also aimed at the wrong path: MEMORY.md does not
// reach an agent through the Read tool, it reaches it through session-start
// auto-injection, and that path truncates this file to its first ~25000
// characters. Roughly 40% of its entries never arrive.
//
// So the fixture that proved the old check was over-eager simultaneously proves
// the new one is necessary. If this test ever goes green-by-silence — if the
// auto-inject flag stops firing here — the detector has gone back to guarding
// only the path nobody loads memory through.
func TestTheReadFineFixtureIsAutoInjectTruncated(t *testing.T) {
	body := []byte(numberedIndex(524))
	r := Check("MEMORY.md", body)

	if r.Chars <= HarnessAutoInjectCapChars {
		t.Fatalf("fixture no longer exercises the finding: %d chars is under the %d-char auto-inject cap", r.Chars, HarnessAutoInjectCapChars)
	}
	if !r.ApproachingAutoInject {
		t.Fatalf("REGRESSION: %d chars is past the %d-char auto-inject cap — the harness injects only a prefix and drops the rest — but the detector stayed silent",
			r.Chars, HarnessAutoInjectCapChars)
	}
	if r.ApproachingRead {
		t.Fatalf("the read budget must NOT be what fires here; that would make this test unable to distinguish the two paths (est %d tokens vs threshold %d)",
			r.EstTokens, r.ThresholdTokens)
	}
	if got := r.Binding(); got != "auto-inject" {
		t.Fatalf("Binding() = %q, want %q — a warn that names the read budget here points the reader at the cliff that is NOT near", got, "auto-inject")
	}

	// Quantify the gap the old scoping left open, so the number is on the
	// record rather than in a commit message.
	lost := r.Chars - HarnessAutoInjectCapChars
	t.Logf("mg-b938's healthy fixture: %d chars vs %d-char auto-inject cap — ~%d chars (~%.0f%%) never injected, while the read check reads it as fine (%d est tokens < %d threshold)",
		r.Chars, HarnessAutoInjectCapChars, lost, 100*float64(lost)/float64(r.Chars), r.EstTokens, r.ThresholdTokens)
}

// TestAutoInjectBudgetIsTheBindingOne states the relationship between the two
// caps that makes checking only the token one unsafe: for ordinary index prose,
// the character budget is exhausted well before the token budget. If a future
// change ever inverts this, the doctor's messaging (which leads with the
// auto-inject path) needs revisiting — so pin it.
func TestAutoInjectBudgetIsTheBindingOne(t *testing.T) {
	// An index sized to sit exactly at the auto-inject cap.
	body := []byte(numberedIndex(524))
	full := string(body)
	if len(full) < HarnessAutoInjectCapChars {
		t.Fatal("fixture too small to trim to the cap")
	}
	atCap := []byte(full[:HarnessAutoInjectCapChars])

	r := Check("MEMORY.md", atCap)
	if r.EstTokens >= HarnessReadCapTokens {
		t.Fatalf("an index at the %d-char auto-inject cap already costs %d tokens (read cap %d) — the character budget is no longer the binding one for prose, and the doctor's messaging assumes it is",
			HarnessAutoInjectCapChars, r.EstTokens, HarnessReadCapTokens)
	}
	t.Logf("at the %d-char auto-inject cap an index costs ~%d tokens — %.1fx headroom under the %d-token read cap, i.e. auto-injection binds first",
		HarnessAutoInjectCapChars, r.EstTokens, float64(HarnessReadCapTokens)/float64(r.EstTokens), HarnessReadCapTokens)
}

// TestWriteCorpus is a generator, not an assertion: it emits the corpus so the
// fixtures can be re-Read through the harness and wantTokens re-measured. It is
// inert unless MEMCHECK_CORPUS_DIR is set.
func TestWriteCorpus(t *testing.T) {
	dir := os.Getenv("MEMCHECK_CORPUS_DIR")
	if dir == "" {
		t.Skip("set MEMCHECK_CORPUS_DIR to emit the calibration corpus for re-measurement")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	for _, c := range corpus() {
		p := filepath.Join(dir, c.name+".md")
		if err := os.WriteFile(p, []byte(c.body), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("%s: %d bytes, %d lines, recorded %d tokens, estimated %d",
			p, len(c.body), strings.Count(c.body, "\n")+1, c.wantTokens, EstimateTokens([]byte(c.body)))
	}
}
